# title:
# author:
# link:
# image:
# description:
# genre:
# completed:

list:
  - type: Продуктовый менеджмент
    books:
      - title: "12 правил жизни. Противоядие от хаоса"
        author: "Джордан Питерсон"
        link: https://www.litres.ru/dzhordan-piterson/12-pravil-zhizni-protivoyadie-ot-haosa/
        image: https://cv8.litres.ru/pub/c/elektronnaya-kniga/cover_415/40685787--.jpg
        description: "Достаточно сложная книга с простым компасом для жизни"
        genre: [Социальная психология]
        completed: читаю
  - type: Проектный менеджмент
    books:
      - title: "Agile Product Management with Scrum: Creating Products that Customers Love"
        author: "Roman Pichler"
        link: https://www.litres.ru/roman-pihler/upravlenie-produktom-v-scrum/
        image: https://images-na.ssl-images-amazon.com/images/I/41NCrarVPVL._SX328_BO1,204,203,200_.jpg
        description: Толковый рассказ о роли владельца продукта в гибкой команде разработки.
        genre: [management, product]
        completed: 2020-12-31
      - title: "Проект «Феникс». Роман о том, как DevOps меняет бизнес к лучшему"
        author: Джин Ким
        link: https://www.litres.ru/dzhin-kim/proekt-feniks-roman-o-tom-kak-devops-menyaet-biznes-k-luchshemu/
        image: https://cv9.litres.ru/pub/c/elektronnaya-kniga/cover_415/11083697-dzhin-kim-proekt-feniks-roman-o-tom-kak-devops-menyaet-biznes-k-luchshemu.jpg
        description: "В легком и развлекательном стиле авторы рассказывают историю, которая знакома всем, кто когда-либо работал в IT. Читатели не только узнают, как использовать методологию DevOps в своих компаниях, они уже никогда не посмотрят на IT прежними глазами. Стоящая чтения книга. Ревью сделаю позже,"
        genre: [management, business]
        completed: 2020-09-30
      - title: "Дизайн привычных вещей"
        author: Дональд Норман
        link: https://www.litres.ru/donald-norman/dizayn-privychnyh-veschey-2/
        image: https://cv9.litres.ru/pub/c/elektronnaya-kniga/cover_415/4953094-donald-norman-dizayn-privychnyh-veschey-2.jpg
        description: "Несколько устаревшее издание когда-то одной из первых популярных книг. Из описания: _Дональд Норман по полочкам раскладывает десятки предметов, которыми мы пользуемся ежедневно, интересно и аргументированно рассуждая об ошибках, совершенных при их проектировании. Красивое – это далеко не всегда еще и удобное. Порой чайник может быть опасным, а входная дверь способна вывести из состояния душевного равновесия._ [Ревью](https://42point.com/posts/design-privichnih-vechey)"
        genre: [design, business]
        completed: Забросил
      - title: "Digital минимализм. Как навести порядок в цифровой среде, перестать зависеть от гаджетов и делать то, что нравится"
        author: Анастасия Рыжина
        link: https://www.litres.ru/anastasiya-ryzhina/digital-minimalizm-kak-navesti-poryadok-v-cifrovoy-sred/?track=from_all_books_my
        image: https://cv1.litres.ru/pub/c/elektronnaya-kniga/cover_330/51697716-anastasiya-ryzhina-digital-minimalizm-kak-navesti-poryadok-v-cifrovoy-sred.jpg
        description: "Набор простых правил, подсказок и намеков с тем как справится наплывом интформации"
        genre: [environment, business, outdoor]
        completed: Читаю
      - title: "Sapiens. Краткая история человечества"
        author: Юваль Ной Харари
        link: https://www.litres.ru/uval-noy-harari/sapiens-kratkaya-istoriya-chelovechestva/
        image: https://cv1.litres.ru/pub/c/elektronnaya-kniga/cover_330/22150614-uval-noy-harari-sapiens-kratkaya-istoriya-chelovechestva.jpg
        description: "Откуда мы взялись? Как развивались? Почему мы такие как есть?"
        genre:
        completed: Читаю
  - type: остальное2
    books:
      - title: "Scrum. Революционный метод управления проектами."
        author: Джефф Сазерленд
        link: https://www.litres.ru/anastasiya-ryzhina/digital-minimalizm-kak-navesti-poryadok-v-cifrovoy-sred/?track=from_all_books_my
        image: https://cv3.litres.ru/pub/c/elektronnaya-kniga/cover_330/11946933-dzheff-sazerlend-scrum-revolucionnyy-metod-upravleniya-proektami.jpg
        description: "Методика Scrum – решение, найденное Джеффом Сазерлендом, чтобы преодолеть классические недостатки управления проектами: отсутствие слаженной работы внутри команды, невыполнение намеченных планов, дублирование задач внутри подразделений и т. д. В отличие от старого «поэтапного» подхода, при котором выбрасываются на ветер огромные средства и который зачастую так ни к чему не приводит, Scrum позволяет выполнять обязательства меньшими силами, в короткие сроки и с низкими затратами, а итоговый продукт отличается отменным качеством. Сегодня Scrum уже прочно закрепилась в управленческом арсенале большинства технологичных компаний мира. Теперь этот инструмент повышения продуктивности доступен и вам."
        genre: [environment, business, outdoor]
        completed: Надо перечитать
  - type: Остальное3
    books:
      - title: "Хаус и философия. Все врут!"
        author: Джейкоби Генри и др.
        link: https://www.litmir.me/bd/?b=122997
        image: https://www.litmir.me/BookBinary/122997/1333227561/CoverNormal.jpg/0
        description: "Книга состоит из восемнадцати эссе-рассуждений принадлежащих перу двадцати философов, описывающих определенные аспекты деятельности и мировоззрения Грегори Хауса."
        genre:
        completed: Надо перечитать
      - title: "Кровь, пот и пиксели. Обратная сторона индустрии видеоигр"
        author: Джейсон Шрейер
        link: https://www.litres.ru/dzheyson-shreyer/krov-pot-i-pikseli-obratnaya-storona-industrii-videoigr/
        image: https://cv4.litres.ru/pub/c/elektronnaya-kniga/cover_330/35245440-dzheyson-shreyer-krov-pot-i-pikseli-obratnaya-storona-industrii-videoigr.jpg
        description: "Лучшая книга об игровой индустрии от известного американского журналиста Джейсона Шрейера."
        genre:
        completed: 2018-09-30
