name: CI

on: push

jobs:
  install_build_show:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1.2" # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: run a script
        run: ruby -v
      - name: install dependancies
        run: bundle install
      # //TODO: склонироватьт репозиторий
      # //TODO: чекаут gh-pages из текущей ветки
      - name: gh-pages
        run: git checkout -b gh-pages
      # // TODO:билд в ветке gh-pages
      - name: jekyll build
        run: bundle exec jekyll build
      - name: go to file
        run: ls _site
      # //TODO: скопировать артефакты
      - name: moving artifacts
        run: |
          find . -maxdepth 1 ! -name '_site' ! -name '.git' ! -name '.gitignore' -exec rm -rf {} \;
          mv _site/* .
          rm -R _site/
      - name: Set git config and add changes
        run: |
          git config --global user.email "${GITHUB_ACTOR}@https://users.noreply.github.com/"
          git config --global user.name "${GITHUB_ACTOR}"

      # // TODO: сделать пуш в gh-pages

      - name: push files
        run: |
          git add -fA
          git commit --allow-empty -m "$(git log -1 --pretty=%B) [ci]"
          git push -f -q origin gh-pages
      - name: success
        run: echo "Deployed Successfully!"
#
# Use GitHub Actions' cache to cache dependencies on servers
#       - uses: actions/cache@v3
#         with:
#           path: vendor/bundle
#           key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
#           restore-keys: |
#             ${{ runner.os }}-gems-
#
#       # Use GitHub Deploy Action to build and deploy to Github
#       - uses: jeffreytse/jekyll-deploy-action@v0.4.0
#         with:
#           provider: 'github'
#           token: ${{ secrets.GITHUB_TOKEN }} # It's your Personal Access Token(PAT)
#           repository: ''             # Default is current repository
#           branch: 'gh-pages'         # Default is gh-pages for github provider
#           jekyll_src: './'           # Default is root directory
#           jekyll_cfg: '_config.yml'  # Default is _config.yml
#           jekyll_baseurl: ''         # Default is according to _config.yml
#           bundler_ver: '>=0'         # Default is latest bundler version
#           cname: ''                  # Default is to not use a cname
#           actor: ''                  # Default is the GITHUB_ACTOR
#           pre_build_commands: ''     # Installing additional dependencies (Arch Linux)
